#!/bin/bash
# Manual Verification Script: Permissions and Hotkey Functionality
# This script provides instructions for manual testing of VoicePaste permissions

set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== VoicePaste Manual Verification Guide ==="
echo ""
echo "This script guides you through manual testing of VoicePaste's"
echo "permission requirements and hotkey functionality."
echo ""
echo "Prerequisites:"
echo "  - macOS 13.0 or later"
echo "  - VoicePaste.app built and ready to run"
echo ""
echo "=== Step 1: Launch Application ==="
echo "  1. Open $PROJECT_DIR/build/Release/VoicePaste.app"
echo "     Or run: open \"\$(find ~/Library/Developer/Xcode/DerivedData -name VoicePaste.app -type d | head -1)\""
echo "  2. Confirm a mic icon appears in the menu bar"
echo "  3. Confirm no Dock icon appears"
echo ""
echo "=== Step 2: Accessibility Permission ==="
echo "  1. System Settings → Privacy & Security → Accessibility"
echo "  2. Find VoicePaste in the list"
echo "  3. Enable the toggle for VoicePaste"
echo "  4. If not listed, the app should prompt you to add it"
echo ""
echo "=== Step 3: Input Monitoring Permission ==="
echo "  1. System Settings → Privacy & Security → Input Monitoring"
echo "  2. Find VoicePaste in the list"
echo "  3. Enable the toggle for VoicePaste"
echo "  4. You may need to restart the app after granting"
echo ""
echo "=== Step 4: Test Hotkey Detection ==="
echo "  1. Open a text editor (TextEdit, Notes, etc.)"
echo "  2. Press and hold Option + Space"
echo "  3. Observe: Menu bar icon should indicate recording state"
echo "  4. Release the keys"
echo "  5. Observe: Recording should stop"
echo ""
echo "=== Step 5: Test API Key Setup ==="
echo "  1. Click the VoicePaste menu bar icon"
echo "  2. Enter your OpenAI API key in the text field"
echo "  3. Click 'Save' to store the key"
echo "  4. Observe: Key should be saved (field may show masked key)"
echo "  5. Verify file exists: ls -la ~/Library/Application\\ Support/VoicePaste/api_key"
echo "  6. Verify permissions are owner-only (should show -rw-------)"
echo "  7. Quit and relaunch the app"
echo "  8. Verify the API key persists after relaunch"
echo "  9. Click 'Clear' to remove the key"
echo "  10. Verify the key is removed and file is deleted"
echo ""
echo "=== Step 6: Test Transcription ==="
echo "  1. Ensure API key is configured (Step 5)"
echo "  2. Open a text editor (TextEdit, Notes, etc.)"
echo "  3. Press and hold Option + Space to record"
echo "  4. Speak a short phrase (e.g., 'VoicePaste test')"
echo "  5. Release Option + Space"
echo "  6. Observe: 'Transcribing...' with animated spinner in overlay"
echo "  7. Verify spinner animates continuously during transcription"
echo "  8. Verify overlay is fully visible and not truncated at screen edge"
echo "  9. Wait for transcription to complete"
echo "  10. Observe: Text should appear in the editor"
echo ""
echo "=== Step 7: Test Error Handling ==="
echo "  1. Clear the API key from settings"
echo "  2. Attempt to record and transcribe"
echo "  3. Observe: Error message about missing API key"
echo ""
echo "=== Verification Checklist ==="
echo "  [ ] App appears in menu bar"
echo "  [ ] No Dock icon visible"
echo "  [ ] Accessibility permission granted"
echo "  [ ] Input Monitoring permission granted"
echo "  [ ] Microphone permission granted"
echo "  [ ] Option+Space hold detected"
echo "  [ ] Recording state indicated"
echo "  [ ] Key release detected"
echo "  [ ] API key can be saved"
echo "  [ ] API key file created with owner-only permissions"
echo "  [ ] API key persists after restart"
echo "  [ ] API key can be cleared"
echo "  [ ] API key file deleted after clear"
echo "  [ ] Transcribing state shown in overlay with animated spinner"
echo "  [ ] Spinner animates continuously during transcription"
echo "  [ ] Transcribing overlay fully visible (not truncated at screen edge)"
echo "  [ ] Transcription result pasted to app"
echo "  [ ] Error shown when API key missing"
echo ""
echo "=== Troubleshooting ==="
echo "  - If hotkey not detected: Check Input Monitoring permission"
echo "  - If paste fails: Check Accessibility permission"
echo "  - If recording fails: Check Microphone permission"
echo "  - If transcription fails: Check API key and internet connection"
echo "  - If app doesn't start: Check Console.app for errors"
echo "  - Restart app after granting any permissions"
echo ""
echo "=== End of Manual Verification Guide ==="
