#!/bin/bash
# Quick test script for microphone permission dialog
set -e

echo "=== VoicePaste Microphone Permission Test ==="
echo ""
echo "This script helps verify the microphone permission dialog appears correctly."
echo ""
echo "Steps to test:"
echo ""
echo "1. Reset microphone permission (if previously granted):"
echo "   tccutil reset Microphone com.were.VoicePaste"
echo ""
echo "2. Build and launch the app:"
echo "   xcodebuild -scheme VoicePaste -configuration Debug build"
echo "   open \"\$(find ~/Library/Developer/Xcode/DerivedData -name VoicePaste.app -type d | head -1)\""
echo ""
echo "3. Grant accessibility permission when prompted (required for hotkey detection)"
echo ""
echo "4. Press and hold Option + Space to trigger recording"
echo ""
echo "5. When system microphone permission dialog appears, click 'Don't Allow'"
echo ""
echo "6. EXPECTED: 'Microphone Access Required' dialog should appear with:"
echo "   - Title: 'Microphone Access Required'"
echo "   - Message: 'VoicePaste needs microphone access to record audio...'"
echo "   - Buttons: 'Open System Settings' and 'Cancel'"
echo ""
echo "7. Click 'Open System Settings' to verify it opens the Microphone pane"
echo ""
echo "=== Console Logs to Watch ==="
echo "Open Console.app and filter for 'VoicePaste' to see debug logs:"
echo "  - [AppState] Requesting microphone permission..."
echo "  - [AppState] Microphone permission result: false"
echo "  - [AppState] Showing microphone access required dialog"
echo ""
