#!/bin/bash
# Manual Verification Script: Permissions and Hotkey Functionality
# This script provides instructions for manual testing of VoicePaste permissions

set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== VoicePaste Manual Verification Guide ==="
echo ""
echo "This script guides you through manual testing of VoicePaste's"
echo "permission requirements and hotkey functionality."
echo ""
echo "Prerequisites:"
echo "  - macOS 13.0 or later"
echo "  - VoicePaste.app built and ready to run"
echo ""
echo "=== Step 1: Launch Application ==="
echo "  1. Open $PROJECT_DIR/build/Release/VoicePaste.app"
echo "     Or run: open \"\$(find ~/Library/Developer/Xcode/DerivedData -name VoicePaste.app -type d | head -1)\""
echo "  2. Confirm a mic icon appears in the menu bar"
echo "  3. Confirm no Dock icon appears"
echo ""
echo "=== Step 2: Accessibility Permission ==="
echo "  1. System Settings → Privacy & Security → Accessibility"
echo "  2. Find VoicePaste in the list"
echo "  3. Enable the toggle for VoicePaste"
echo "  4. If not listed, the app should prompt you to add it"
echo ""
echo "=== Step 3: Input Monitoring Permission ==="
echo "  1. System Settings → Privacy & Security → Input Monitoring"
echo "  2. Find VoicePaste in the list"
echo "  3. Enable the toggle for VoicePaste"
echo "  4. You may need to restart the app after granting"
echo ""
echo "=== Step 4: Test Hotkey Detection ==="
echo "  1. Open a text editor (TextEdit, Notes, etc.)"
echo "  2. Press and hold Option + Space"
echo "  3. Observe: Menu bar icon should indicate recording state"
echo "  4. Release the keys"
echo "  5. Observe: Recording should stop"
echo ""
echo "=== Step 5: Test Paste Simulation ==="
echo "  1. With text editor focused"
echo "  2. Trigger paste simulation (after voice transcription)"
echo "  3. Observe: Text should appear in the editor"
echo ""
echo "=== Verification Checklist ==="
echo "  [ ] App appears in menu bar"
echo "  [ ] No Dock icon visible"
echo "  [ ] Accessibility permission granted"
echo "  [ ] Input Monitoring permission granted"
echo "  [ ] Option+Space hold detected"
echo "  [ ] Recording state indicated"
echo "  [ ] Key release detected"
echo "  [ ] Paste simulation works"
echo ""
echo "=== Troubleshooting ==="
echo "  - If hotkey not detected: Check Input Monitoring permission"
echo "  - If paste fails: Check Accessibility permission"
echo "  - If app doesn't start: Check Console.app for errors"
echo "  - Restart app after granting any permissions"
echo ""
echo "=== End of Manual Verification Guide ==="
